# Fleet Tracker Prometheus Configuration
# Monitoring configuration for the Fleet Tracker system

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fleet-tracker'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Fleet Tracker Backend API
  - job_name: 'fleet-tracker-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['database:5432']
    # Note: Requires postgres_exporter sidecar

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    # Note: Requires redis_exporter sidecar

  # MQTT Broker (if Mosquitto exports metrics)
  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto:9001']

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

# Remote write configuration (optional)
# remote_write:
#   - url: "https://your-remote-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
