apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: fleet-tracker-staging
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8003"
    spec:
      containers:
        - name: location-service
          image: ghcr.io/your-github-username/fleet-tracker-location-service:latest # <-- Replace with your GHCR path
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: location-service-secrets
                  key: database_url
            - name: MQTT_BROKER_URL
              value: "mqtt://mosquitto-service:1883"
            - name: REDIS_URL
              value: "redis://redis-service:6379"

