apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: fleet-tracker-staging
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8004"
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/your-github-username/fleet-tracker-notification-service:latest # <-- Replace with your GHCR path
          ports:
            - containerPort: 8004
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: database_url
            - name: REDIS_URL
              value: "redis://redis-service:6379"

