apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: fleet-tracker-staging
  labels:
    app: vehicle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8002"
    spec:
      containers:
        - name: vehicle-service
          image: ghcr.io/your-github-username/fleet-tracker-vehicle-service:latest # <-- Replace with your GHCR path
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vehicle-service-secrets
                  key: database_url
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8001"

