apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fleet-tracker-production
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/your-github-username/fleet-tracker-auth-service:latest # <-- Replace with your GHCR path
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: fleet-tracker-config # We will create this later for non-sensitive config
          env:
            - name: AUTH_DB_URL
              valueFrom:
                secretKeyRef:
                  name: fleet-tracker-secrets
                  key: AUTH_DB_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fleet-tracker-secrets
                  key: JWT_SECRET_KEY

