apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fleet-tracker-production
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/your-github-username/fleet-tracker-frontend:latest # <-- Replace with your GHCR path
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://api-gateway.fleet-tracker-production.svc.cluster.local"

