apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: fleet-tracker-production
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout

    listener 1883
    protocol mqtt

    # Add authentication settings here if needed
    # allow_anonymous false
    # password_file /mosquitto/config/password_file

