name: CI - Backend Services

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, auth-service, location-service, notification-service, vehicle-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/${{ matrix.service }}/requirements.txt
          if [ -f services/${{ matrix.service }}/requirements-dev.txt ]; then pip install -r services/${{ matrix.service }}/requirements-dev.txt; fi

      - name: Run tests
        run: |
          cd services/${{ matrix.service }}
          pytest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fleet-tracker-${{ matrix.service }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

